export const RENDER_HOME = "RENDER_HOME";
export const RENDER_ABOUT = "RENDER_ABOUT";
export const RENDER_PROJECTS = "RENDER_PROJECTS";
export const RENDER_CONTACT = "RENDER_CONTACT";
export const RENDER_SKILLS = "RENDER_SKILLS";
export const CHANGE_LENGUAGE = "CHANGE_LENGUAGE";
